spring:
  application:
    name: store
  config:
    import: optional:file:.env[.properties]
  datasource:
    url: jdbc:mysql://localhost:3306/store?createDatabaseIfNotExist=true
    username: ${DATABASE_USER}
    password: ${DATABASE_PASSWORD}


stripe:
  apiUrl: https://api.stripe.com
  timeout: 1000
  enabled: true
  currencies: USD,EUR,GBP

paypal:
  apiUrl: https://api.paypal.com
  timeout: 1000
  enabled: false
  currencies: USD,EUR,GBP

mail:
  host: smtp.gmail.com
  port: 587